(setq debug-on-error t)
(package-initialize)
(message "Loading dud ...")
(load "~/.emacs.d/dud/dud.el")
(message "Initializing dud ...")
(dud-init)
(load "~/Projects/netspring/tools/emacs/netspring.el")
(put 'narrow-to-page 'disabled nil)
(put 'overwrite-mode 'disabled nil)
(put 'narrow-to-region 'disabled nil)
